version: '3.8'

networks:
  good_network:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: hezzl
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - good_network

  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - good_network

  nats:
    image: bitnami/nats:latest
    container_name: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
      - nats_data:/nats-data
    networks:
      - good_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - good_network

volumes:
  postgres_data:
  clickhouse_data:
  nats_data:
  redis_data:

